// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQGTciiuPxmQl-pXNPYJLW5mjKzD7wHOc',
    appId: '1:13915332767:android:138d79a3bf3ec14c5b82aa',
    messagingSenderId: '13915332767',
    projectId: 'flutterfirebase-c5a1b',
    databaseURL: 'https://flutterfirebase-c5a1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterfirebase-c5a1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4cqV1cNk5qKFClYWvUA-M-wLPOOSM_AQ',
    appId: '1:13915332767:ios:cf2264f06f48a4385b82aa',
    messagingSenderId: '13915332767',
    projectId: 'flutterfirebase-c5a1b',
    databaseURL: 'https://flutterfirebase-c5a1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterfirebase-c5a1b.appspot.com',
    iosClientId: '13915332767-arc3pgscqgvfq1hd4ukeqiglehckud1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.manojproject',
  );
}
